version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: support_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d support_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI application
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/support_db
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: